---

baseURL: "http://taketwo.tylerbutler.com/"
languageCode: "en-us"
title: "Take Two"
theme: "dark-rainbow"

params:
  avatar: "/images/hugo.png"
  displayauthor: false
  
  # pygments
  PygmentsUseClasses: yes
  PygmentsCodeFences: yes

  theme:
    bigfoot:
      enabled: yes
    typekit_id: my_typekit
    sharing:
      enabled: yes
      facebook:
        enabled: yes
        app_id: my_app_id
      twitter:
        enabled: yes
    comments:
      enabled: yes
      provider: "disqus"
      account: my_account
      