---

baseURL: "http://taketwo.tylerbutler.com/"
languageCode: "en-us"
title: "Take Two"
theme: taketwo
Paginate: 4
enableEmoji: yes

# staticDir:
#   - 'themes/taketwo/semantic/dist'
#   - 'static'

permalinks:
  pages: /:slug/
  posts: /:year/:month/:slug/

taxonomies:
  language: languages
  person: people
  place: places
  tag: tags
  storyline: storylines

params:
  description: "The Butlers in PNG"

sectionPagesMenu: main
